### ISSUE TITLE
Where are the plugin settings?

### ISSUE THREAD

**Issue by JulioPradera** [shagabutdinov/sublime-statement#1]
I downloaded this plugin because it is said to be mandatory to use the Semicolon plugin. However, it changes many of the Sublime native shortcuts that I use.
I tried to find the keymap, in order to disable the shortcuts, but for some reason this plugin is not appearing in "Preferences -> Package Settings".

**Comment by shagabutdinov** [comment]
There is `setting.sublime_enhanced_keybindings` but seems it's not applied to some shortcuts... Do you mind to opening a PR with this change? Alternatively, you may clone this plugin to the sublime `plugins` folder (do manual installation) and remove shortcuts files, this should work too.
